services:
  jordanp-env:
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
    image: atidyshirt/jordanp-env:[tag]
    volumes:
      - $(pwd):/home/ws

version: '1.0'
